server:
  port: 9000
logging:
  level:
    org.springframework.security: trace
spring:
  flyway:
    locations: classpath:db/migration
  application:
    name: auth-service
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
  datasource:
    url: jdbc:h2:mem:auth_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      connection:
        provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider

front:
  url: http://localhost:3000