server:
  port: 9000
logging:
  level:
    org.springframework.security: trace
spring:
  flyway:
    locations: classpath:db/migration
  application:
    name: auth-service
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/f_m
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      connection:
        provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider

