server:
  port: 8070

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks

    #feign:
  #oauth2:
    #enabled: true
    #clientRegistrationId: spring
logging:
  level:
    org.springframework.security: trace