server:
  port: 8090
logging:
  level:
    org.springframework.security: trace
spring:
  flyway:
    locations: classpath:db/migration
  application:
    name: fertilizer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          feign:
            provider: feign
            client-id: feign
            client-secret: secret
            authorization-grant-type: client_credentials
            redirect-uri: "http://localhost:8090"
            scope: openid,clients,profile
        provider:
          feign:
            #token-uri: http://localhost:9000/oauth2/access-token
            issuer-uri: http://localhost:9000
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: feign
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/f_s
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      connection:
        provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider
