server:
  port: 8090
logging:
  level:
    org.springframework.security: trace
spring:
  h2:
    console:
      enabled: true
  flyway:
    locations: classpath:db/migration
  application:
    name: fertilizer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          feign:
            provider: feign
            client-id: feign
            client-secret: secret
            authorization-grant-type: client_credentials
            redirect-uri: "http://localhost:8090"
            scope: openid,clients,profile
        provider:
          feign:
            token-uri: http://localhost:9000/oauth2/token
            authorization-uri: http://localhost:9000/oauth2/authorize
            user-info-uri: http://localhost:9000/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            #issuer-uri: http://localhost:9000
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: feign
  datasource:
    url: jdbc:h2:mem:fertilizers
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
        connection:
          provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider
front:
  url: http://localhost:3000